- name: Build dynamic limits_config dictionary
  set_fact:
    loki_limits_config: >-
      {{
        dict(
          allow_structured_metadata=true,
          max_cache_freshness_per_query="10m",
          query_timeout="300s",
          reject_old_samples_max_age="168h",
          split_queries_by_interval="15m",
          volume_enabled=true
        )
        | combine({"reject_old_samples": ingester_limit_config.reject_old_samples} if ingester_limit_config.reject_old_samples is defined else {})
        | combine({"ingestion_rate_mb": ingester_limit_config.ingestion_rate_mb} if ingester_limit_config.ingestion_rate_mb is defined else {})
        | combine({"ingestion_burst_size_mb": ingester_limit_config.ingestion_burst_size_mb} if ingester_limit_config.ingestion_burst_size_mb is defined else {})
      }}

- name: debug loki values
  debug:
    var: loki_limits_config

- name: Generate Loki values file
  template:
    src: values-loki.yaml.j2
    dest: /tmp/loki-values.yaml
