- name: Add Grafana Helm repo
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: "https://grafana.github.io/helm-charts"

- name: Update Helm repositories
  command: helm repo update
  changed_when: true
